#!/bin/bash


# paths to individual algorithm executables 
export MIXMHCPRED=/Users/eawilso6/projects/Covid-19/EnsembleMHC-Covid19/EnsembleMHC/MHC-I_Software/MixMHCpred-2.0.2/MixMHCpred
export NETMHC=/Users/eawilso6/projects/Covid-19/EnsembleMHC-Covid19/EnsembleMHC/MHC-I_Software/netMHC-4.0/netMHC
export NETMHCPAN=/Users/eawilso6/projects/Covid-19/EnsembleMHC-Covid19/EnsembleMHC/MHC-I_Software/netMHCpan-4.0/netMHCpan
export NETMHCSTABPAN=/Users/eawilso6/projects/Covid-19/EnsembleMHC-Covid19/EnsembleMHC/MHC-I_Software/netMHCstabpan-1.0/netMHCstabpan
export PICKPOCKET=/Users/eawilso6/projects/Covid-19/EnsembleMHC-Covid19/EnsembleMHC/MHC-I_Software/pickpocket-1.1/PickPocket


#absolute path to EnsembleMHC
export ENSEMBLEMHC_PATH=/Users/eawilso6/projects/Covid-19/EnsembleMHC-Covid19/EnsembleMHC/

